const factfiles = [
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 2,
    name: 'Miyawaki Sakura',
    birthdate: 'March 19th 1998',
    nationality: 'Japanese',
    zodiac: 'Pisces',
    color: 'Pastel Pink',
  },
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
]

export default factfiles;