const factfiles = [
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Purple',
  },
  {
    id: 2,
    name: 'Miyawaki Sakura',
    birthdate: '19th March 1998',
    nationality: 'Japanese',
    zodiac: 'Pisces',
    color: 'Pastel Pink',
  },
  {
    id: 3,
    name: 'Kang Hyewon',
    birthdate: '5th July 1999',
    nationality: 'Korean',
    zodiac: 'Cancer',
    color: 'Coral',
  },
  {
    id: 4,
    name: 'Choi Yena',
    birthdate: '29th September 1999',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Yellow',
  },
  {
    id: 5,
    name: 'Lee Chaeyeon',
    birthdate: '11th January 2000',
    nationality: 'Korean',
    zodiac: 'Capricorn',
    color: 'Blue Mint',
  },
  {
    id: 6,
    name: 'Kim Chaewon',
    birthdate: '1st August 2000',
    nationality: 'Korean',
    zodiac: 'Leo',
    color: 'Mint',
  },
  {
    id: 7,
    name: 'Kim Minju',
    birthdate: '5th February 2001',
    nationality: 'Korean',
    zodiac: 'Aquarius',
    color: 'White',
  },
  {
    id: 8,
    name: 'Yabuki Nako',
    birthdate: '18th June 2001',
    nationality: 'Japanese',
    zodiac: 'Gemini',
    color: 'Sky Blue',
  },
  {
    id: 9,
    name: 'Honda Hitomi',
    birthdate: '6th October 2001',
    nationality: 'Japanese',
    zodiac: 'Libra',
    color: 'Peach',
  },
  {
    id: 10,
    name: 'Jo Yuri',
    birthdate: '22nd October 2001',
    nationality: 'Korean',
    zodiac: 'Libra',
    color: 'Orange',
  },
  {
    id: 11,
    name: 'Ahn Yujin',
    birthdate: '1st September 2003',
    nationality: 'Korean',
    zodiac: 'Virgo',
    color: 'Blue',
  },
  {
    id: 12,
    name: 'Jang Wonyoung',
    birthdate: '31st August 2004',
    nationality: 'Korean',
    zodiac: 'Virgo',
    color: 'Pink',
  },
]

export default factfiles;