const factfiles = [
  {
    id: 1,
    name: 'Kwon Eunbi',
    birthdate: '27th September 1995',
    nationality: 'Korean',
    zodiac: 'Libra',
    colour: 'Purple',
    img: './images/eunbi.webp',
  },
  {
    id: 2,
    name: 'Miyawaki Sakura',
    birthdate: '19th March 1998',
    nationality: 'Japanese',
    zodiac: 'Pisces',
    colour: 'Pastel Pink',
    img: './images/sakura.webp',
  },
  {
    id: 3,
    name: 'Kang Hyewon',
    birthdate: '5th July 1999',
    nationality: 'Korean',
    zodiac: 'Cancer',
    colour: 'Coral',
    img: './images/hyewon.webp',
  },
  {
    id: 4,
    name: 'Choi Yena',
    birthdate: '29th September 1999',
    nationality: 'Korean',
    zodiac: 'Libra',
    colour: 'Yellow',
    img: './images/yena.webp',
  },
  {
    id: 5,
    name: 'Lee Chaeyeon',
    birthdate: '11th January 2000',
    nationality: 'Korean',
    zodiac: 'Capricorn',
    colour: 'Blue Mint',
    img: './images/chaeyeon.webp',
  },
  {
    id: 6,
    name: 'Kim Chaewon',
    birthdate: '1st August 2000',
    nationality: 'Korean',
    zodiac: 'Leo',
    colour: 'Mint',
    img: './images/chaewon.webp',
  },
  {
    id: 7,
    name: 'Kim Minju',
    birthdate: '5th February 2001',
    nationality: 'Korean',
    zodiac: 'Aquarius',
    colour: 'White',
    img: './images/minju.webp',
  },
  {
    id: 8,
    name: 'Yabuki Nako',
    birthdate: '18th June 2001',
    nationality: 'Japanese',
    zodiac: 'Gemini',
    colour: 'Sky Blue',
    img: './images/nako.webp',
  },
  {
    id: 9,
    name: 'Honda Hitomi',
    birthdate: '6th October 2001',
    nationality: 'Japanese',
    zodiac: 'Libra',
    colour: 'Peach',
    img: './images/hitomi.webp',
  },
  {
    id: 10,
    name: 'Jo Yuri',
    birthdate: '22nd October 2001',
    nationality: 'Korean',
    zodiac: 'Libra',
    colour: 'Orange',
    img: './images/yuri.webp',
  },
  {
    id: 11,
    name: 'Ahn Yujin',
    birthdate: '1st September 2003',
    nationality: 'Korean',
    zodiac: 'Virgo',
    colour: 'Blue',
    img: './images/yujin.webp',
  },
  {
    id: 12,
    name: 'Jang Wonyoung',
    birthdate: '31st August 2004',
    nationality: 'Korean',
    zodiac: 'Virgo',
    colour: 'Pink',
    img: './images/wonyoung.webp',
  },
]

export default factfiles;